apiVersion: v1
kind: ConfigMap
metadata:
  name: prizm-service-core-config
  namespace: default
  labels:
    app: prizm-service-core
    tier: backend
data:
  SPRING_PROFILES_ACTIVE: "prod"
  LOG_LEVEL: "INFO"
