apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prizm-service-core
  namespace: default
spec:
  parentRefs:
    - name: prizm-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/api"
          headers:
            - name: ":authority"
              value: "prizm.run"
      backendRefs:
        - name: prizm-service-core
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: "/api/mgmt"
          headers:
            - name: ":authority"
              value: "mgmt.prizm.run"
      backendRefs:
        - name: prizm-service-core
          port: 8080
