apiVersion: v1
kind: Service
metadata:
  name: prizm-service-core
  namespace: default
  labels:
    app: prizm-service-core
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: prizm-service-core
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
