apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: prizm-service-core
  labels:
    app: prizm-service-core

data:
  DB_HOST: "{{ .Values.prizm.service.core.db.host }}"
  DB_PORT: "{{ .Values.prizm.service.core.db.port }}"
  DB_USERNAME: "{{ .Values.prizm.service.core.db.username }}"
  DB_NAME: "{{ .Values.prizm.service.core.db.name }}"

  REDIS_HOST: "{{ .Values.prizm.service.core.redis.host }}"
  REDIS_PORT: "{{ .Values.prizm.service.core.redis.port }}"

  S3_ENDPOINT: "{{ .Values.prizm.service.core.s3.endpoint }}"
  S3_REGION: "{{ .Values.prizm.service.core.s3.region }}"
  S3_ACCESS_KEY: "{{ .Values.prizm.service.core.s3.accessKey }}"
  S3_BUCKET: "{{ .Values.prizm.service.core.s3.bucket }}"

  RABBITMQ_HOST: "{{ .Values.prizm.service.core.rabbitmq.host }}"
  RABBITMQ_PORT: "{{ .Values.prizm.service.core.rabbitmq.port }}"
  RABBITMQ_STOMP_PORT: "{{ .Values.prizm.service.core.rabbitmq.stompPort }}"
  RABBITMQ_USERNAME: "{{ .Values.prizm.service.core.rabbitmq.username }}"

  OAUTH2_GITHUB_CLIENT_ID: "{{ .Values.prizm.service.core.oauth2.github.clientId }}"

  OAUTH2_GOOGLE_CLIENT_ID: "{{ .Values.prizm.service.core.oauth2.google.clientId }}"

  JWT_ACCESS_TOKEN_EXPIRATION: "{{ .Values.prizm.service.core.db.host }}"
  JWT_REFRESH_TOKEN_EXPIRATION: "{{ .Values.prizm.service.core.db.host }}"

  COOKIE_DOMAIN: "{{ .Values.ingress.hosts }}"

  TRANSLATE_API_URL: "{{ .Values.prizm.service.core.translate.apiUrl }}"