apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: prizm-service-core
  labels:
    app: prizm-service-core

spec:
  type: ClusterIP

  selector:
    app: prizm-service-core

  ports:
    - name: http
      port: 80
      targetPort: 8080