apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: prizm-web-user
  labels:
    app: prizm-web-user

spec:
  type: ClusterIP

  selector:
    app: prizm-web-user

  ports:
    - name: http
      port: 80
      targetPort: 3000