apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: prizm-service-ai
  labels:
    app: prizm-service-ai

data:
  OPENAI_MODEL: "{{ .Values.prizm.openai.model }}"
  OPENAI_CHAT_MODEL: "{{ .Values.prizm.openai.chatModel }}"

  S3_ENDPOINT: "{{ .Values.prizm.s3.endpoint }}"
  S3_REGION: "{{ .Values.prizm.s3.region }}"
  S3_ACCESS_KEY: "{{ .Values.prizm.s3.accessKey }}"
  S3_BUCKET: "{{ .Values.prizm.s3.bucket }}"

  QDRANT_HOST: "{{ .Values.prizm.qdrant.host }}"
  QDRANT_PORT: "{{ .Values.prizm.qdrant.port }}"