apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: prizm-service-ai
  labels:
    app: prizm-service-ai

spec:
  type: ClusterIP

  selector:
    app: prizm-service-ai

  ports:
    - name: http
      port: 80
      targetPort: 8000