apiVersion: v1
kind: ConfigMap
metadata:
  name: prizm-service-ai-config
  namespace: default
  labels:
    app: prizm-service-ai
    tier: backend
data:
  SPRING_PROFILES_ACTIVE: "prod"
  LOG_LEVEL: "INFO"
