apiVersion: apps/v1
kind: Deployment
metadata:
  name: prizm-service-ai
  namespace: default
  labels:
    app: prizm-service-ai
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prizm-service-ai
  template:
    metadata:
      labels:
        app: prizm-service-ai
        tier: backend
    spec:
      containers:
        - name: ai
          image: "ghcr.io/himedia-no1/prizm-service-ai:main"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: prizm-service-ai-config
