apiVersion: v1
kind: Service
metadata:
  name: prizm-service-ai
  namespace: default
  labels:
    app: prizm-service-ai
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: prizm-service-ai
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
