apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: prizm-web-landing
  labels:
    app: prizm-web-landing

spec:
  replicas: 1

  selector:
    matchLabels:
      app: prizm-web-landing

  template:
    metadata:
      labels:
        app: prizm-web-landing

    spec:
      containers:
        - name: prizm-web-landing
          image: 'ghcr.io/himedia-no1/prizm-web-landing:{{ index .Values.image "prizm-web-landing-tag" }}'
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP