apiVersion: apps/v1
kind: Deployment
metadata:
  name: prizm-web-landing
  namespace: {{ .Release.Namespace }}
  labels:
    app: prizm-web-landing
    tier: frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: prizm-web-landing

  template:
    metadata:
      labels:
        app: prizm-web-landing
        tier: frontend

    spec:
      containers:
        - name: prizm-web-landing
          image: "ghcr.io/himedia-no1/prizm-web-landing:{{ index .Values.image.tag "prizm-web-landing" }}"
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP