apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prizm-web-landing
  namespace: {{ .Release.Namespace }}
  labels:
    app: prizm-web-landing
    tier: frontend

spec:
  parentRefs:
    - namespace: {{ .Values.gateway.namespace }}
      name: {{ .Values.gateway.name }}

  hostnames:
    - "dev.prizm.run"

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: prizm-web-landing
          port: 80