apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: prizm-web-landing
  labels:
    app: prizm-web-landing

spec:
  type: ClusterIP

  selector:
    app: prizm-web-landing

  ports:
    - name: http
      port: 80
      targetPort: 8080