apiVersion: v1
kind: Service
metadata:
  name: prizm-web-landing
  namespace: {{ .Release.Namespace }}
  labels:
    app: prizm-web-landing
    tier: frontend

spec:
  type: ClusterIP

  selector:
    app: prizm-web-landing

  ports:
    - name: http
      port: 80
      targetPort: 8080