ingress:
  hosts: "dev.prizm.run"
  clusterIssuer: "selfsigned-cluster-issuer"

prizm:
  prizmWebUserImageTag: 5554928eabd35eed68650b9719f685e6072b772d
  prizmServiceCoreImageTag: tag
  prizmServiceAiImageTag: tag

  postgresql:
    host: "postgresql"
    port: "5432"
    username: "prizm"
    password: ""
    name: "prizm"

  redis:
    host: "redis"
    port: "6379"
    username: ""
    password: ""
    database: "0"

  s3:
    endpoint: "http://minio:9000"
    region: "us-east-1"
    accessKey: "prizm"
    secretKey: ""
    bucket: "file"
    publicUrl: "https://dev.prizm.run"

  rabbitmq:
    host: "rabbitmq"
    port: "5672"
    stompPort: "61613"
    username: "prizm"
    password: ""

  qdrant:
    host: "qdrant"
    port: "6333"
    apiKey: ""

  openai:
    apiKey: ""
    model: "gpt-4o-mini"
    chatModel: "gpt-4o"

  oauth2:
    github:
      clientId: "Ov23livpsn3U5r3C54yY"
      clientSecret: ""
    google:
      clientId: "839875779709-6guut6eh19ua7pajr6bv6dusn8m7rd0a.apps.googleusercontent.com"
      clientSecret: ""

  jwt:
    secret: ""
    access-token-expiration: "600000"
    refresh-token-expiration: "604800000"