image:
    prizm-web-landing-tag: 8350955f8129f39638a4cd01a689f8e841f47c6f
    prizm-web-user-tag: 90750a52c61df0707efee1b1d32dc1fc407df41b
    prizm-web-admin-tag: tag
    prizm-service-core-tag: tag
    prizm-service-ai-tag: tag

ingress:
  clusterIssuer: selfsigned-cluster-issuer
  hosts: dev.prizm.run