image:
    prizm-web-landing-tag: 8350955f8129f39638a4cd01a689f8e841f47c6f
    prizm-web-user-tag: tag
    prizm-web-admin-tag: tag
    prizm-service-core-tag: tag
    prizm-service-ai-tag: tag

gateway:
  namespace: nginx-gateway
  name: http-gateway