image:
    prizm-web-landing-tag: 8350955f8129f39638a4cd01a689f8e841f47c6f
    prizm-web-user-tag: d3c4385772e52ed1a5b1c5d98ddf8b362857f73f
    prizm-web-admin-tag: tag
    prizm-service-core-tag: tag
    prizm-service-ai-tag: tag

ingress:
  clusterIssuer: selfsigned-cluster-issuer
  hosts: dev.prizm.run