image:
    prizm-web-landing-tag: tag
    prizm-web-user-tag: tag
    prizm-web-admin-tag: tag
    prizm-service-core-tag: tag
    prizm-service-ai-tag: tag

gateway:
  namespace: nginx-gateway
  name: http-gateway