apiVersion: apps/v1
kind: Deployment
metadata:
  name: prizm-web-user
  namespace: default
  labels:
    app: prizm-web-user
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prizm-web-user
  template:
    metadata:
      labels:
        app: prizm-web-user
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: "ghcr.io/himedia-no1/prizm-web-user:main"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: static-files
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-config
          configMap:
            name: prizm-web-user-nginx-config
        - name: static-files
          emptyDir: {}