apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prizm-web-user
  namespace: default
spec:
  parentRefs:
    - name: prizm-gateway
  hostnames:
    - "prizm.run"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: prizm-web-user
          port: 80
