apiVersion: v1
kind: Service
metadata:
  name: prizm-web-user
  namespace: default
  labels:
    app: prizm-web-user
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: prizm-web-user
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP