apiVersion: v1
kind: Service
metadata:
  name: prizm-web-admin
  namespace: default
  labels:
    app: prizm-web-admin
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: prizm-web-admin
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
